name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Postgresql and postgis
        uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql password: 'password'
          postgresql user: 'root'
          postgresql db: 'meili_testing'

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: pdo, pdo_pgsql, bcmath
          tools: phpunit
          coverage: none

      - name: Meilisearch
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Laravel scout index
        run: php artisan scout:index ads

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: psql
          DB_DATABASE: 'meili_testing'
          DB_USERNAME: 'root'
          DB_PASSWORD: 'password'
          DB_PORT: 5432
        run: vendor/bin/phpunit
